---
options:
  collate: utf8_unicode_ci
  charset: utf8 


# CAMPAIGN FINANCE DATA
  
OsDonation:
  connection: raw
  columns:
    cycle:
      type: string(4)
      notnull: true
      primary: true
    row_id:
      type: string(7)
      notnull: true
      primary: true
    donor_id: string(12)
    donor_name: string(34)
    recipient_id: string(9)
    employer_name: string(40)
    parent_name: string(40)
    industry_id: string(5)
    date: date
    amount: integer
    street: string(40)
    city: string(18)
    state: string(2)
    zip: string(5)
    recipient_code: string(2)
    transaction_type: string(3)
    committee_id: string(9)
    intermediate_id: string(9)
    gender: string(1)
    employer_raw: string(35)
    fec_id: string(11)
    org_raw: string(38)
    title_raw: string(38)
    source: string(5)
    donor_name_last: string(30)
    donor_name_first: string(20)
    donor_name_middle: string(20)
    donor_name_suffix: string(20)
    donor_name_nick: string(20)

OsPacDonation:
  connection: raw
  columns:
    cycle:
      type: string(4)
      notnull: true
      primary: true
    row_id:
      type: string(7)
      notnull: true
      primary: true
    committee_id:
      type: string(9)
      notnull: true
    recipient_crp_id:
      type: string(9)
      notnull: true
    amount: integer
    date: date
    industry_id: string(5)
    transaction_type: string(3)
    direct: string(1)
    recipient_fec_id: 
      type: string(9)
      notnull: true
    
OsCandidate:
  connection: raw
  columns:
    cycle:
      type: string(4)
      notnull: true
    fec_id:
      type: string(9)
      notnull: true
    candidate_id:
      type: string(9)
      notnull: true
      primary: true
    name: string(40)
    party: string(1)
    district: string(4)
    district_current: string(4)
    is_current: string(1)
    ran: string(1)
    type: string(1)
    recipient_code: string(2)
    nopacs: string(1)
    name_last: string(30)
    name_first: string(30)
    name_middle: string(30)
    name_suffix: string(10)
    name_nick: string(20)

OsCommittee:
  connection: raw
  columns:
    cycle:
      type: string(4)
      notnull: true
    committee_id:
      type: string(9)
      notnull: true
      primary: true
    name: string(40)
    affiliate: string(40)
    parent: string(40)
    recipient_id: string(9)
    recipient_code: string(2)
    candidate_id: string(9)
    party: string(1)
    industry_id: string(5)
    source: string(5)
    sensitive: string(1)
    foreign: 
      type: boolean
      notnull: true
    active:
      type: boolean
      notnull: true    

OsEntityDonor:
  connection: main
  columns:
    entity_id:
      type: integer
      notnull: true
    donor_id: string(12)
    match_code: integer
    is_verified:
      type: boolean
      notnull: true
      default: false
    is_processed:
      type: boolean
      notnull: true
      default: false
    is_synced:
      type: boolean
      notnull: true
      default: true
    reviewed_by_user_id: integer
    reviewed_at: timestamp
    locked_by_user_id: integer
    locked_at: timestamp

OsEntityTransaction:
  connection: main
  columns:
    id:
      type: integer(4)
      primary: true
      autoincrement: true
    entity_id:
      type: integer(4)
      notnull: true
    cycle:
      type: string(4)
      notnull: true
    transaction_id: 
      type: string(7)
      notnull: true
    match_code: integer
    is_verified:
      type: boolean
      notnull: true
      default: false
    is_processed:
      type: boolean
      notnull: true
      default: false
    is_synced:
      type: boolean
      notnull: true
      default: true
    reviewed_by_user_id: integer
    reviewed_at: timestamp
    locked_by_user_id: integer
    locked_at: timestamp
      
OsEntityPreprocess:
  connection: main
  columns:
    entity_id:
      type: integer
      notnull: true
    cycle:
      type: string(4)
      notnull: true
    processed_at:
      type: timestamp
      notnull: true
      
# LOBBYING DATA

OsLobbying:
  connection: raw
  columns:
    uniq_id: 
      type: string(36)
      notnull: true
      primary: true
    registrant_raw: string(100)
    registrant: string(40)
    isfirm: string(1)
    client_raw: string(100)
    client: string(40)
    ultorg: string(40)
    amount:
      type: decimal(15)
      scale: 2
    catcode: string(5)
    source: string(5)
    self: string(1)
    include_nsfs: string(1)
    is_used: string(1)
    ind: string(1)
    year: string(4)
    type: string(4)
    typelong: string(80)
    org_id: string(10)
    affiliate: string(1)
  indexes:
    registrant_idx:
      fields: [registrant]
    ultorg_idx:
      fields: [ultorg]
    client_idx:
      fields: [client]
    catcode_idx:
      fields: [catcode]

# Connected to OsLobbying via uniq_id
OsLobbyist:
  connection: raw
  columns:
    uniq_id: 
      type: string(36)
      notnull: true
    lobbyist_raw: string(50)
    lobbyist: string(50)
    lobbyist_id: string(12)
    year: string(4)
    official_position: string(100)
    cid: string(15)
    formercongmem: string(10)
    name_first: string(20)
    name_middle: string(20)
    name_last: string(30)
    name_suffix: string(20)
    name_nick: string(20)
  indexes:
    uniq_id_idx:
      fields: [uniq_id]
    lobbyist_id_idx:
      fields: [lobbyist_id]
    name_idx:
      fields: [name_last, name_middle]

# Connected to OsLobbying via ultorg and client
OsLobbyingIndustry:
  connection: raw
  columns:
    ultorg: string(40)
    client: string(40)
    total:
      type: decimal(15)
      scale: 2
    year: string(4)
    catcode: string(5)
  indexes:
    catcode_idx:
      fields: [catcode, year, ultorg]

# Connected to OsLobbying via uniq_id
OsLobbyingAgency:
  connection: raw
  columns:
    uniq_id:
      type: string(36)
      notnull: true
    agency_id: 
      type: string(3)
      notnull: true
    agency: 
      type: string(80)
      notnull: true
  indexes:
    uniq_id_idx:
      fields: [uniq_id]
    agency_id_idx:
      fields: [agency_id]
    agency_idx:
      fields: [agency]

# Connected to OsLobbying via uniq_id
OsLobbyingIssue:
  connection: raw
  columns:
    si_id:
      type: integer(4)
      notnull: true
      primary: true
    uniq_id:
      type: string(36)
      notnull: true
    issue_id: string(3)
    issue: string(50)
    specific_issue: blob
    year: string(4)
  indexes:
    uniq_id_idx:
      fields: [uniq_id]
    issue_id_idx:
      fields: [uniq_id]
    

# Connected to OsLobbyingIssue via si_id
OsLobbyingBill:
  connection: raw
  columns:
    b_id: integer(4)
    si_id: integer(4)
    cong_no: string(3)
    bill_name: string(15)
  indexes:
    si_id_idx:
      fields: [si_id]
    bill_name_idx:
      fields: [bill_name]
      
      
#CRP INDUSTRY CODES

OsCategory:
  columns:
    category_id: 
      type: string(10)
      notnull: true
    category_name:
      type: string(100)
      notnull: true
    industry_id:
      type: string(10)
      notnull: true
    industry_name:
      type: string(100)
      notnull: true
    sector_name:
      type: string(100)
      notnull: true
  relations:
    Entity:
      refClass: OsEntityCategory
      local: category_id
      foreign: entity_id
  indexes:
    unique_id:
      fields: category_id
      type: unique
    unique_name:
      fields: category_name
      type: unique    

OsEntityCategory:
  actAs: [Timestampable]
  columns:
    entity_id:
      type: integer
      notnull: true
    category_id:
      type: string(10)
      notnull: true
    source:
      type: string(200)
  relations:
    Entity:
      local: entity_id
      foreign: id
      onUpdate: CASCADE
      onDelete: CASCADE
    OsCategory:
      local: category_id
      foreign: category_id
      onUpdate: CASCADE
      onDelete: CASCADE
  indexes:
    uniqueness:
      fields: [entity_id, category_id]
      type: unique